-- MySQL Script generated by MySQL Workbench
-- Sun Aug 24 16:10:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TP_Base_de_Datos_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TP_Base_de_Datos_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TP_Base_de_Datos_1` DEFAULT CHARACTER SET utf8 ;
USE `TP_Base_de_Datos_1` ;

-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`autopartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`autopartes` (
  `idautopartes` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `medidas` INT NULL,
  `stock` INT NOT NULL,
  `precio` INT NULL,
  PRIMARY KEY (`idautopartes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`Provedor` (
  `idProvedor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`idProvedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`linea_de_montaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`linea_de_montaje` (
  `idlinea_de_montaje` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlinea_de_montaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`modelo` (
  `idmodelo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `año` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `fecha_de_fabricacion` DATE NOT NULL,
  `hora_de_fabricacion` TIME NULL,
  `linea_de_montaje_idlinea_de_montaje` INT NOT NULL,
  PRIMARY KEY (`idmodelo`),
  INDEX `fk_modelo_linea_de_montaje1_idx` (`linea_de_montaje_idlinea_de_montaje` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_linea_de_montaje1`
    FOREIGN KEY (`linea_de_montaje_idlinea_de_montaje`)
    REFERENCES `TP_Base_de_Datos_1`.`linea_de_montaje` (`idlinea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`estacion_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`estacion_de_trabajo` (
  `idestacion_de_trabajo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tarea` VARCHAR(45) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_finalizacion` TIME NOT NULL,
  `linea_de_montaje_idlinea_de_montaje` INT NOT NULL,
  PRIMARY KEY (`idestacion_de_trabajo`, `linea_de_montaje_idlinea_de_montaje`),
  INDEX `fk_estacion_de_trabajo_linea_de_montaje1_idx` (`linea_de_montaje_idlinea_de_montaje` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_de_trabajo_linea_de_montaje1`
    FOREIGN KEY (`linea_de_montaje_idlinea_de_montaje`)
    REFERENCES `TP_Base_de_Datos_1`.`linea_de_montaje` (`idlinea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`empleado` (
  `idempleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `sueldo` VARCHAR(45) NULL,
  `turno` TIME NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`insumos` (
  `idautopartes` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `medidas` INT NULL,
  `stock` INT NOT NULL,
  `precio` INT NULL,
  PRIMARY KEY (`idautopartes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`concesionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`concesionarios` (
  `idconcesionarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idconcesionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`Provedor_has_autopartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`Provedor_has_autopartes` (
  `Provedor_idProvedor` INT NOT NULL,
  `autopartes_idautopartes` INT NOT NULL,
  PRIMARY KEY (`Provedor_idProvedor`, `autopartes_idautopartes`),
  INDEX `fk_Provedor_has_autopartes_autopartes1_idx` (`autopartes_idautopartes` ASC) VISIBLE,
  INDEX `fk_Provedor_has_autopartes_Provedor_idx` (`Provedor_idProvedor` ASC) VISIBLE,
  CONSTRAINT `fk_Provedor_has_autopartes_Provedor`
    FOREIGN KEY (`Provedor_idProvedor`)
    REFERENCES `TP_Base_de_Datos_1`.`Provedor` (`idProvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Provedor_has_autopartes_autopartes1`
    FOREIGN KEY (`autopartes_idautopartes`)
    REFERENCES `TP_Base_de_Datos_1`.`autopartes` (`idautopartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`estacion_de_trabajo_has_insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`estacion_de_trabajo_has_insumos` (
  `estacion_de_trabajo_idestacion_de_trabajo` INT NOT NULL,
  `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje` INT NOT NULL,
  `insumos_idautopartes` INT NOT NULL,
  PRIMARY KEY (`estacion_de_trabajo_idestacion_de_trabajo`, `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje`, `insumos_idautopartes`),
  INDEX `fk_estacion_de_trabajo_has_insumos_insumos1_idx` (`insumos_idautopartes` ASC) VISIBLE,
  INDEX `fk_estacion_de_trabajo_has_insumos_estacion_de_trabajo1_idx` (`estacion_de_trabajo_idestacion_de_trabajo` ASC, `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_de_trabajo_has_insumos_estacion_de_trabajo1`
    FOREIGN KEY (`estacion_de_trabajo_idestacion_de_trabajo` , `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje`)
    REFERENCES `TP_Base_de_Datos_1`.`estacion_de_trabajo` (`idestacion_de_trabajo` , `linea_de_montaje_idlinea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_de_trabajo_has_insumos_insumos1`
    FOREIGN KEY (`insumos_idautopartes`)
    REFERENCES `TP_Base_de_Datos_1`.`insumos` (`idautopartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`Provedor_has_insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`Provedor_has_insumos` (
  `Provedor_idProvedor` INT NOT NULL,
  `insumos_idautopartes` INT NOT NULL,
  PRIMARY KEY (`Provedor_idProvedor`, `insumos_idautopartes`),
  INDEX `fk_Provedor_has_insumos_insumos1_idx` (`insumos_idautopartes` ASC) VISIBLE,
  INDEX `fk_Provedor_has_insumos_Provedor1_idx` (`Provedor_idProvedor` ASC) VISIBLE,
  CONSTRAINT `fk_Provedor_has_insumos_Provedor1`
    FOREIGN KEY (`Provedor_idProvedor`)
    REFERENCES `TP_Base_de_Datos_1`.`Provedor` (`idProvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Provedor_has_insumos_insumos1`
    FOREIGN KEY (`insumos_idautopartes`)
    REFERENCES `TP_Base_de_Datos_1`.`insumos` (`idautopartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`autopartes_has_estacion_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`autopartes_has_estacion_de_trabajo` (
  `autopartes_idautopartes` INT NOT NULL,
  `estacion_de_trabajo_idestacion_de_trabajo` INT NOT NULL,
  `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje` INT NOT NULL,
  PRIMARY KEY (`autopartes_idautopartes`, `estacion_de_trabajo_idestacion_de_trabajo`, `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje`),
  INDEX `fk_autopartes_has_estacion_de_trabajo_estacion_de_trabajo1_idx` (`estacion_de_trabajo_idestacion_de_trabajo` ASC, `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje` ASC) VISIBLE,
  INDEX `fk_autopartes_has_estacion_de_trabajo_autopartes1_idx` (`autopartes_idautopartes` ASC) VISIBLE,
  CONSTRAINT `fk_autopartes_has_estacion_de_trabajo_autopartes1`
    FOREIGN KEY (`autopartes_idautopartes`)
    REFERENCES `TP_Base_de_Datos_1`.`autopartes` (`idautopartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autopartes_has_estacion_de_trabajo_estacion_de_trabajo1`
    FOREIGN KEY (`estacion_de_trabajo_idestacion_de_trabajo` , `estacion_de_trabajo_linea_de_montaje_idlinea_de_montaje`)
    REFERENCES `TP_Base_de_Datos_1`.`estacion_de_trabajo` (`idestacion_de_trabajo` , `linea_de_montaje_idlinea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TP_Base_de_Datos_1`.`concesionarios_has_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TP_Base_de_Datos_1`.`concesionarios_has_modelo` (
  `concesionarios_idconcesionarios` INT NOT NULL,
  `modelo_idmodelo` INT NOT NULL,
  PRIMARY KEY (`concesionarios_idconcesionarios`, `modelo_idmodelo`),
  INDEX `fk_concesionarios_has_modelo_modelo1_idx` (`modelo_idmodelo` ASC) VISIBLE,
  INDEX `fk_concesionarios_has_modelo_concesionarios1_idx` (`concesionarios_idconcesionarios` ASC) VISIBLE,
  CONSTRAINT `fk_concesionarios_has_modelo_concesionarios1`
    FOREIGN KEY (`concesionarios_idconcesionarios`)
    REFERENCES `TP_Base_de_Datos_1`.`concesionarios` (`idconcesionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concesionarios_has_modelo_modelo1`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `TP_Base_de_Datos_1`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
